<?php

/**
 * @file
 * Hook implementations for Quant sitemap.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function quant_sitemap_form_quant_seed_settings_alter(&$form, $form_state) {
  $form['quant_seed_sitemap'] = array(
    '#type' => 'checkbox',
    '#title' => t('Export sitemaps'),
    '#default_value' => variable_get('quant_seed_sitemap', FALSE),
  );
}

/**
 * Implements hook_quant_seed_alter().
 */
function quant_sitemap_quant_seed_alter(&$batch) {
  if (!variable_get('quant_seed_sitemap', FALSE)) {
    return;
  }

  $sitemaps = xmlsitemap_sitemap_load_multiple(FALSE);

  foreach ($sitemaps as $sitemap) {
    $batch['operations'][] = array(
      'quant_seed',
      url($sitemap->uri['path'], $sitemap->uri['options'])
    );
  }
}
