 # Schema for the configuration files of the purge_queuer_url module.
quant_purger.settings:
  type: config_object
  label: 'Quant purger settings.'
  mapping:
    tag_blacklist:
      label: 'A list of string tags that will not trigger a queue.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in the cache tag.'
        translatable: false
    path_blacklist:
      label: 'A list of string patterns that will not get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in a fully qualified URL.'
        translatable: false

quant_purger.settings.*:
  type: config_entity
  label: 'Section Purger'
  mapping:

    #
    # Instance metadata:
    #
    id:
      type: string
      translatable: false
    name:
      type: string
      translatable: false
    invalidationtype:
      type: string
      translatable: false

    #
    # Performance settings:
    #
    runtime_measurement:
      type: boolean
      translatable: false
    timeout:
      type: float
      translatable: false
    connect_timeout:
      type: float
      translatable: false
    cooldown_time:
      type: float
      translatable: false
    max_requests:
      type: integer
      translatable: false

    #
    # Success resolution:
    #
    http_errors:
      type: boolean
      translatable: false
