quant_purger.settings:
  type: config_object
  label: 'Quant Purger Queuer Settings'
  mapping:
    tag_blocklist:
      label: 'A list of tags that will not get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in the cache tag.'
        translatable: false
    tag_allowlist:
      label: 'A list of tags that can get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that can be present in the cache tag.'
        translatable: false
    path_blocklist:
      label: 'A list of paths that will not get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in a fully qualified URL.'
        translatable: false
    path_allowlist:
      label: 'A list of paths that can not get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that can be present in a fully qualified URL.'
        translatable: false

// @todo Why is this under the queuer settings?
quant_purger.settings.*:
  type: config_entity
  label: 'Quant Purger Settings'
  mapping:

    #
    # Instance metadata:
    #
    id:
      type: string
      translatable: false
    name:
      type: string
      translatable: false
    invalidation_type:
      type: string
      translatable: false

    #
    # Performance settings:
    #
    runtime_measurement:
      type: boolean
      translatable: false
    timeout:
      type: float
      translatable: false
    connect_timeout:
      type: float
      translatable: false
    cooldown_time:
      type: float
      translatable: false
    max_requests:
      type: integer
      translatable: false

    #
    # Success resolution:
    #
    http_errors:
      type: boolean
      translatable: false
