# Schema for the configuration files of the quant_purger module.
quant_purger.settings:
  type: config_object
  label: 'Quant purger settings.'
  mapping:
    tag_blocklist:
      label: 'Cache tags that will not trigger a queue.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in the cache tag.'
        translatable: false
    path_blocklist:
      label: 'Path patterns that will not get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that cannot be present in a path.'
        translatable: false
    tag_allowlist:
      label: 'Cache tags that will always trigger a queue.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that must be present in the cache tag.'
        translatable: false
    path_allowlist:
      label: 'Path patterns that will always get queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'String that must be present in a path.'
        translatable: false
