<?php

/**
 * @file
 * Quant Search: index content to Quant hosted search and build search pages.
 */

module_load_include('inc', 'quant_search', 'quant_search.api');

/**
 * Implements hook_permission().
 */
function quant_search_permission() {
  return array(
    'administer quant search' => array(
      'title' => t('Administer Quant Search'),
      'description' => t('Configure the Quant search index and search pages.'),
      'restrict access' => TRUE,
    ),
  );
}
